### PR TITLE
Implement setCache

### PR DESCRIPTION
**Pull request by lasseborly**
This is going to alllow for the selective update of caches. A performance enhancement if one is not making use of either google or bing.

### CODE REVIEW

**Comment by JoyceBabu** [comment]
@lasseborly Thank you for the PR. Wouldn't it be better to add a `setCache` method to compliment the `getCache` method?


```php
public function setCache($cacheList)
{
    $this->cacheList = $cacheList;
}
```
Then you can filter the list once

```php
$updater = new Ennexa\AmpCache\Update(PATH_TO_YOUR_PRIVATE_KEY);
$updater->setCache(array_filter($updater->getCache(), fn($cache) => $cache->id === 'google'));
$status = $updater->purge('https://www.prokerala.com/health/?amp=1');
```

**Comment by lasseborly** [comment]
Certainly 👍 Do you want to go ahead with the implementation of that or do you want me to follow it to the door?

**Comment by JoyceBabu** [comment]
If you can update your PR with the above suggested change, I would much appreciate that.

**Comment by lasseborly** [comment]
Will do that in the morning. Thanks.

**Comment by lasseborly** [comment]
Here we go @JoyceBabu :clap: 
Thanks a ton.

**Comment by JoyceBabu** [comment]
@lasseborly Thank you. I will cut a patch release with this change soon.

**Pull request merged**
